import Head from "next/head";
import Layout from "@/components/layout/layout";
import Hero from "@/components/hero";
import Stats from "@/components/stats";
// import Team from "@/components/team";
// import About from "@/components/about_team";
import AboutUs from "@/components/abou_us";
import Offer from "@/components/offer";
import Dream from "@/components/dream_home";
import Review from "@/components/reviews"
import Contact from "@/components/contact";
import Form from "@/components/new_contact"

export default function Home() {
  return (
    <div>
      <Head>
        <title>BuchGroup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BuchFavicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Stats />
        {/* <Team />
        <About /> */}
        <AboutUs />
        <Offer />
        <Dream />
        <Review />
        {/* <Contact /> */}
        <Form/>
      </Layout>
    </div>
  );
}
